openapi: 3.0.0
info:
  version: 0.0.1
  title: "Godspeed: Sample Microservice"
  description: Sample API calls demonstrating the functionality of Godspeed framework
  termsOfService: http://swagger.io/terms/
  contact:
    name: Mindgrep Technologies Pvt Ltd
    email: talktous@mindgrep.com
    url: https://docs.mindgrep.com/docs/microservices/intro
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:3000
paths:
  "/postgres/menuitems/{id}":
    get:
      summary: Fetch MenuItems
      description: Fetch MenuItems from database
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        content:
          application/json:
            schema:
              type: object
    put:
      summary: Update a MenuItems
      description: Update MenuItems from database
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/postgres/MenuItems"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        content:
          application/json:
            schema:
              type: object
    delete:
      summary: Delete a MenuItems
      description: Delete MenuItems from database
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        content:
          application/json:
            schema:
              type: object
  /postgres/menuitems:
    post:
      summary: Create a new MenuItems
      description: Create MenuItems from database
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/postgres/MenuItems"
      responses:
        content:
          application/json:
            schema:
              type: object
  /postgres/menuitems/search:
    post:
      summary: Fetch multiple MenuItems
      description: Fetch multiple MenuItems from database
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        content:
          application/json:
            schema:
              type: array
  "/postgres/restaurant/{id}":
    get:
      summary: Fetch Restaurant
      description: Fetch Restaurant from database
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        content:
          application/json:
            schema:
              type: object
    put:
      summary: Update a Restaurant
      description: Update Restaurant from database
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/postgres/Restaurant"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        content:
          application/json:
            schema:
              type: object
    delete:
      summary: Delete a Restaurant
      description: Delete Restaurant from database
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        content:
          application/json:
            schema:
              type: object
  /postgres/restaurant:
    post:
      summary: Create a new Restaurant
      description: Create Restaurant from database
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/definitions/postgres/Restaurant"
      responses:
        content:
          application/json:
            schema:
              type: object
  /postgres/restaurant/search:
    post:
      summary: Fetch multiple Restaurant
      description: Fetch multiple Restaurant from database
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        content:
          application/json:
            schema:
              type: array
definitions:
  postgres:
    Restaurant:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        name:
          type: string
        since:
          type: string
          format: date-time
        isOpen:
          type: boolean
          default: false
        opsStartTime:
          type: string
          format: date-time
        opsEndTime:
          type: string
          format: date-time
        ownerId:
          type: integer
          nullable: true
        slug:
          type: string
        description:
          type: string
          nullable: true
        location:
          type: string
    MenuItems:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        price:
          type: integer
        couponCode:
          type: array
          items:
            type: string
        restaurantId:
          type: integer
